# Generated by Django 5.0.7 on 2024-07-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0054_alter_customuser_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='credit',
            field=models.IntegerField(default=200),
        ),
    ]
