# Generated by Django 5.0.7 on 2024-08-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0055_customuser_is_subscribed_alter_customuser_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_supporter',
            field=models.BooleanField(default=False),
        ),
    ]
